"use client";

import Image from "next/image";
import { FormEvent, KeyboardEvent, PointerEvent, useEffect, useMemo, useRef, useState } from "react";

type Player = { id: string; firstName: string };
type Lineup = Record<string, Player[]>;
type Point = { x: number; y: number };
export type AnnotationType = "pass" | "run" | "dribble" | "shot";
export type TacticAnnotation = { id: string; type: AnnotationType; from: Point; to: Point };
export type TacticLayout = { positions: Record<string, Point>; ball: Point; annotations?: TacticAnnotation[] };
export type Scenario = "attack" | "defense" | "corner";
export type TacticTemplate = Scenario | "blank";
export type CustomTactic = { id: string; name: string; layout: TacticLayout; baseScenario: TacticTemplate; createdAt: string; deleted?: boolean };
export type TacticEntry = TacticLayout | CustomTactic;
type DragTarget = { kind: "position"; id: string } | { kind: "ball" };

const positions = [
  { id: "st", short: "ST", label: "Sturm" }, { id: "lf", short: "LF", label: "Linker Flügel" }, { id: "rf", short: "RF", label: "Rechter Flügel" },
  { id: "zm", short: "ZM", label: "Zentrales Mittelfeld" }, { id: "zdm", short: "ZDM", label: "Defensives Mittelfeld" },
  { id: "lv", short: "LV", label: "Linke Verteidigung" }, { id: "iv", short: "IV", label: "Innenverteidigung" }, { id: "rv", short: "RV", label: "Rechte Verteidigung" }, { id: "tw", short: "TW", label: "Torwart" },
] as const;

export const scenarioLabels: Record<Scenario, string> = { attack: "Angriff", defense: "Verteidigung", corner: "Ecke" };
const basePositions = { st: { x: 50, y: 15 }, lf: { x: 11, y: 34 }, rf: { x: 89, y: 34 }, zm: { x: 41, y: 43 }, zdm: { x: 59, y: 53 }, lv: { x: 22, y: 68 }, iv: { x: 50, y: 65 }, rv: { x: 78, y: 68 }, tw: { x: 50, y: 88 } };
const defaultLayouts: Record<Scenario, TacticLayout> = {
  attack: { positions: { st: { x: 50, y: 12 }, lf: { x: 14, y: 29 }, rf: { x: 86, y: 29 }, zm: { x: 39, y: 39 }, zdm: { x: 58, y: 49 }, lv: { x: 18, y: 61 }, iv: { x: 50, y: 65 }, rv: { x: 82, y: 61 }, tw: { x: 50, y: 88 } }, ball: { x: 50, y: 43 } },
  defense: { positions: { st: { x: 50, y: 28 }, lf: { x: 18, y: 44 }, rf: { x: 82, y: 44 }, zm: { x: 40, y: 53 }, zdm: { x: 59, y: 59 }, lv: { x: 18, y: 70 }, iv: { x: 50, y: 72 }, rv: { x: 82, y: 70 }, tw: { x: 50, y: 88 } }, ball: { x: 50, y: 35 } },
  corner: { positions: { st: { x: 50, y: 11 }, lf: { x: 65, y: 15 }, rf: { x: 79, y: 20 }, zm: { x: 43, y: 23 }, zdm: { x: 35, y: 39 }, lv: { x: 24, y: 51 }, iv: { x: 49, y: 48 }, rv: { x: 72, y: 45 }, tw: { x: 50, y: 88 } }, ball: { x: 92, y: 7 } },
};

function isCustomEntry(value: TacticEntry | undefined): value is CustomTactic { return Boolean(value && "layout" in value); }
function cloneLayout(layout: TacticLayout): TacticLayout { return { positions: Object.fromEntries(Object.entries(layout.positions).map(([id, point]) => [id, { ...point }])), ball: { ...layout.ball }, annotations: (layout.annotations ?? []).map((item) => ({ ...item, from: { ...item.from }, to: { ...item.to } })) }; }
function blankLayout(): TacticLayout { return { positions: Object.fromEntries(Object.entries(basePositions).map(([id, point]) => [id, { ...point }])), ball: { x: 50, y: 50 }, annotations: [] }; }
function templateLayout(template: TacticTemplate): TacticLayout { return template === "blank" ? blankLayout() : cloneLayout(defaultLayouts[template]); }
function completeLayout(value: TacticLayout | undefined, scenario: TacticTemplate): TacticLayout {
  const fallback = templateLayout(scenario);
  return { positions: Object.fromEntries(positions.map((position) => [position.id, value?.positions?.[position.id] ?? fallback.positions[position.id]])), ball: value?.ball ?? fallback.ball, annotations: value?.annotations ?? fallback.annotations ?? [] };
}
function PlayerAvatar({ firstName }: { firstName: string }) { return <Image className="player-avatar" src={`/api/player-image?name=${encodeURIComponent(firstName)}`} alt="" width={36} height={36} unoptimized loading="lazy" />; }

export default function TacticsBoard({ lineupId, eventTitle, tactics, onSave, onCreate, onRename, onDuplicate, onDelete }: {
  lineupId: string; eventTitle: string; tactics: Record<string, TacticEntry>; onSave: (scenario: string, layout: TacticLayout) => Promise<void>;
  onCreate: (name: string, template: TacticTemplate, layout: TacticLayout) => Promise<string>; onRename: (id: string, name: string) => Promise<void>; onDuplicate: (id: string, layout: TacticLayout) => Promise<string>; onDelete: (id: string) => Promise<void>;
}) {
  const customEntries = useMemo(() => Object.values(tactics).filter((entry): entry is CustomTactic => isCustomEntry(entry) && !entry.deleted).sort((a, b) => a.createdAt.localeCompare(b.createdAt)), [tactics]);
  const [scenario, setScenario] = useState<string>("attack");
  const [lineup, setLineup] = useState<Lineup>({}); const [lineupSource, setLineupSource] = useState(eventTitle);
  const activeEntry = tactics[scenario]; const activeCustom = isCustomEntry(activeEntry) ? activeEntry : undefined;
  const activeTemplate: TacticTemplate = activeCustom?.baseScenario ?? (scenario in scenarioLabels ? scenario as Scenario : "blank");
  const [layout, setLayout] = useState(() => completeLayout(activeCustom?.layout ?? (activeEntry as TacticLayout | undefined), activeTemplate));
  const [dragging, setDragging] = useState<DragTarget | null>(null); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [presenting, setPresenting] = useState(false); const [tool, setTool] = useState<"select" | AnnotationType>("select"); const [drawStart, setDrawStart] = useState<Point | null>(null);
  const [dialog, setDialog] = useState<"create" | "rename" | null>(null); const [draftName, setDraftName] = useState(""); const [draftTemplate, setDraftTemplate] = useState<TacticTemplate>("attack");
  const boardRef = useRef<HTMLDivElement>(null); const layoutRef = useRef(layout);

  useEffect(() => { const next = completeLayout(activeCustom?.layout ?? (activeEntry as TacticLayout | undefined), activeTemplate); setLayout(next); layoutRef.current = next; }, [scenario, tactics]);
  useEffect(() => { let cancelled = false; async function loadLineup() { try { const response = await fetch(`/api/lineup?lineupId=${encodeURIComponent(lineupId)}`, { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Spieltagskader konnte nicht geladen werden."); let nextLineup = data.lineup ?? {}; let source = eventTitle; if (!Object.values(nextLineup as Lineup).some((players) => players.length)) { const fallbackResponse = await fetch("/api/lineup?lineupId=default", { cache: "no-store" }); const fallback = await fallbackResponse.json(); if (fallbackResponse.ok) { nextLineup = fallback.lineup ?? {}; source = "Allgemeine Aufstellung"; } } if (!cancelled) { setLineup(nextLineup); setLineupSource(source); } } catch (reason) { if (!cancelled) setMessage(reason instanceof Error ? reason.message : "Spieltagskader konnte nicht geladen werden."); } } void loadLineup(); return () => { cancelled = true; }; }, [eventTitle, lineupId]);
  useEffect(() => { if (!presenting) return; const exit = (event: globalThis.KeyboardEvent) => { if (event.key === "Escape") setPresenting(false); }; window.addEventListener("keydown", exit); return () => window.removeEventListener("keydown", exit); }, [presenting]);
  const activePlayers = useMemo(() => Object.fromEntries(positions.map((position) => [position.id, lineup[position.id]?.[0]])), [lineup]);
  function updateLayout(next: TacticLayout) { layoutRef.current = next; setLayout(next); }
  function pointFromPointer(event: PointerEvent) { const rect = boardRef.current?.getBoundingClientRect(); if (!rect) return null; return { x: Math.min(94, Math.max(6, ((event.clientX - rect.left) / rect.width) * 100)), y: Math.min(94, Math.max(6, ((event.clientY - rect.top) / rect.height) * 100)) }; }
  function annotationPoint(event: PointerEvent<SVGSVGElement>) { return pointFromPointer(event as unknown as PointerEvent); }
  function beginDraw(event: PointerEvent<SVGSVGElement>) { if (tool === "select") return; event.preventDefault(); setDrawStart(annotationPoint(event)); }
  function finishDraw(event: PointerEvent<SVGSVGElement>) { if (!drawStart || tool === "select") return; const end = annotationPoint(event); if (!end) return; const distance = Math.hypot(end.x - drawStart.x, end.y - drawStart.y); if (distance < 3) { setDrawStart(null); return; } const next = { ...layoutRef.current, annotations: [...(layoutRef.current.annotations ?? []), { id: `annotation-${Date.now().toString(36)}`, type: tool, from: drawStart, to: end }] }; setDrawStart(null); updateLayout(next); void persist(next); }
  function moveTarget(target: DragTarget, point: Point) { const current = layoutRef.current; updateLayout(target.kind === "ball" ? { ...current, ball: point } : { ...current, positions: { ...current.positions, [target.id]: point } }); }
  function beginDrag(event: PointerEvent<HTMLButtonElement>, target: DragTarget) { event.preventDefault(); event.currentTarget.setPointerCapture(event.pointerId); setDragging(target); }
  function moveDrag(event: PointerEvent<HTMLButtonElement>) { if (!dragging) return; const point = pointFromPointer(event); if (point) moveTarget(dragging, point); }
  async function finishDrag(event: PointerEvent<HTMLButtonElement>) { if (!dragging) return; if (event.currentTarget.hasPointerCapture(event.pointerId)) event.currentTarget.releasePointerCapture(event.pointerId); setDragging(null); await persist(layoutRef.current); }
  async function persist(next: TacticLayout) { setSaving(true); setMessage(""); try { await onSave(scenario, next); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Taktik konnte nicht gespeichert werden."); } finally { setSaving(false); } }
  function moveByKeyboard(event: KeyboardEvent<HTMLButtonElement>, target: DragTarget) { const delta = event.shiftKey ? 3 : 1; const point = target.kind === "ball" ? layoutRef.current.ball : layoutRef.current.positions[target.id]; if (!point) return; const next = { ...point }; if (event.key === "ArrowLeft") next.x -= delta; else if (event.key === "ArrowRight") next.x += delta; else if (event.key === "ArrowUp") next.y -= delta; else if (event.key === "ArrowDown") next.y += delta; else return; event.preventDefault(); moveTarget(target, { x: Math.min(94, Math.max(6, next.x)), y: Math.min(94, Math.max(6, next.y)) }); void persist(layoutRef.current); }
  async function resetScenario() { const next = templateLayout(activeTemplate); updateLayout(next); await persist(next); }
  async function clearAnnotations() { const next = { ...layoutRef.current, annotations: [] }; updateLayout(next); await persist(next); }
  async function submitDialog(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const name = draftName.trim().replace(/\s+/g, " ").slice(0, 40); if (!name) return; if (dialog === "rename" && activeCustom) { await onRename(activeCustom.id, name); setDialog(null); return; } if (dialog === "create") { if (customEntries.some((entry) => entry.name.localeCompare(name, "de", { sensitivity: "base" }) === 0)) { setMessage("Dieser Taktikname ist bereits vergeben."); return; } const id = await onCreate(name, draftTemplate, templateLayout(draftTemplate)); setScenario(id); setDialog(null); } }
  async function duplicate() { if (!activeCustom) return; const id = await onDuplicate(activeCustom.id, cloneLayout(layoutRef.current)); setScenario(id); }
  async function remove() { if (!activeCustom || !window.confirm(`„${activeCustom.name}“ wirklich löschen?`)) return; await onDelete(activeCustom.id); setScenario("attack"); }

  return <div className={`tactics-workspace${presenting ? " presenting" : ""}`}>
    <div className="tactics-toolbar"><div><p className="section-index">TAKTIKTAFEL</p><strong>{lineupSource}</strong></div><div className="tactics-actions">{activeCustom && <><button className="text-button" type="button" onClick={() => { setDraftName(activeCustom.name); setDialog("rename"); }}>Umbenennen</button><button className="text-button" type="button" onClick={() => void duplicate()}>Duplizieren</button><button className="text-button danger" type="button" onClick={() => void remove()}>Löschen</button></>}<button className="text-button" type="button" onClick={() => void resetScenario()}>Zurücksetzen</button><button className="primary-button" type="button" onClick={() => setPresenting((current) => !current)}>{presenting ? "Präsentation beenden" : "Präsentieren"}</button></div></div>
    <div className="tactics-scenarios" role="tablist" aria-label="Taktik auswählen">{(Object.keys(scenarioLabels) as Scenario[]).map((item) => <button key={item} type="button" role="tab" aria-selected={scenario === item} className={scenario === item ? "active" : ""} onClick={() => setScenario(item)}>{scenarioLabels[item]}</button>)}{customEntries.map((entry) => <button key={entry.id} type="button" role="tab" aria-selected={scenario === entry.id} className={scenario === entry.id ? "active custom" : "custom"} onClick={() => setScenario(entry.id)}>{entry.name}</button>)}<button className="tactics-add" type="button" onClick={() => { setDraftName(""); setDraftTemplate("attack"); setDialog("create"); }}>+ Neue Taktik</button><span className={saving ? "saving active" : "saving"} aria-live="polite">{saving ? "Speichert …" : "Gespeichert"}</span></div>
    <div className="tactics-drawing-toolbar" role="toolbar" aria-label="Taktik zeichnen"><span>Zeichnen:</span>{([{ key: "select", label: "Auswahl" }, { key: "pass", label: "Pass" }, { key: "run", label: "Laufweg" }, { key: "dribble", label: "Dribbling" }, { key: "shot", label: "Torschuss" }] as const).map((item) => <button key={item.key} type="button" className={tool === item.key ? "active" : ""} onClick={() => { setTool(item.key); setDrawStart(null); }}>{item.label}</button>)}<button type="button" className="clear-drawing" onClick={() => void clearAnnotations()} disabled={!layout.annotations?.length}>Zeichnungen löschen</button></div>
    {message && <p className="coach-notice" role="status">{message}</p>}
    <div className="tactics-pitch pitch-wrap" ref={boardRef} aria-label={`${activeCustom?.name ?? scenarioLabels[scenario as Scenario] ?? "Taktik"} – taktische Positionen`}>
      <div className="pitch-label top">ANGRIFF</div><div className="pitch-label middle">MITTELFELD</div><div className="pitch-label bottom">ABWEHR</div><div className="pitch-lines" aria-hidden="true"><div className="touchline" /><div className="halfway" /><div className="center-circle" /><div className="center-dot" /><div className="box box-top" /><div className="goal-box goal-box-top" /><div className="box box-bottom" /><div className="goal-box goal-box-bottom" /></div>
      <svg className={`tactics-drawing-layer${tool !== "select" ? " drawing-active" : ""}`} viewBox="0 0 100 100" preserveAspectRatio="none" aria-label="Taktische Lauf- und Passwege" onPointerDown={beginDraw} onPointerUp={finishDraw}><defs><marker id="tactic-arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="4" markerHeight="4" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" /></marker></defs>{(layout.annotations ?? []).map((item) => <line key={item.id} className={`tactic-line ${item.type}`} x1={item.from.x} y1={item.from.y} x2={item.to.x} y2={item.to.y} markerEnd="url(#tactic-arrow)" />)}{drawStart && <line className={`tactic-line preview ${tool}`} x1={drawStart.x} y1={drawStart.y} x2={drawStart.x} y2={drawStart.y} />}</svg>
      {positions.map((position) => { const player = activePlayers[position.id]; const point = layout.positions[position.id] ?? basePositions[position.id]; return <button className={`position-node has-players tactic-position${dragging?.kind === "position" && dragging.id === position.id ? " dragging" : ""}`} key={position.id} type="button" style={{ left: `${point.x}%`, top: `${point.y}%` }} aria-label={`${position.label}${player ? `: ${player.firstName}` : ": nicht besetzt"}. Verschieben`} onPointerDown={(event) => beginDrag(event, { kind: "position", id: position.id })} onPointerMove={moveDrag} onPointerUp={(event) => void finishDrag(event)} onPointerCancel={(event) => void finishDrag(event)} onKeyDown={(event) => moveByKeyboard(event, { kind: "position", id: position.id })}><span className="position-badge">{position.short}</span><span className="position-names">{player ? <span className="position-player"><PlayerAvatar firstName={player.firstName} /><strong>{player.firstName}</strong></span> : <em>Nicht besetzt</em>}</span></button>; })}
      <button className={`tactics-ball${dragging?.kind === "ball" ? " dragging" : ""}`} type="button" style={{ left: `${layout.ball.x}%`, top: `${layout.ball.y}%` }} aria-label="Ball verschieben" onPointerDown={(event) => beginDrag(event, { kind: "ball" })} onPointerMove={moveDrag} onPointerUp={(event) => void finishDrag(event)} onPointerCancel={(event) => void finishDrag(event)} onKeyDown={(event) => moveByKeyboard(event, { kind: "ball" })}>⚽</button>
    </div><p className="tactics-help">Positionen und Ball verschieben. Zeichenmodus wählen, dann auf dem Feld ziehen. Wege werden automatisch gespeichert.</p>
    {dialog && <div className="modal-backdrop" role="presentation"><div className="coach-modal tactics-dialog" role="dialog" aria-modal="true" aria-labelledby="tactics-dialog-title"><p className="section-index">TAKTIKEN</p><h2 id="tactics-dialog-title">{dialog === "create" ? "Neue Taktik" : "Taktik umbenennen"}</h2><form onSubmit={(event) => void submitDialog(event)}><label htmlFor="tactic-name">Name</label><input id="tactic-name" value={draftName} onChange={(event) => setDraftName(event.target.value)} maxLength={40} autoFocus required />{dialog === "create" && <label htmlFor="tactic-template">Vorlage<select id="tactic-template" value={draftTemplate} onChange={(event) => setDraftTemplate(event.target.value as TacticTemplate)}><option value="attack">Angriff</option><option value="defense">Verteidigung</option><option value="corner">Ecke</option><option value="blank">Leeres Feld</option></select></label>}<div className="modal-actions"><button className="text-button" type="button" onClick={() => setDialog(null)}>Abbrechen</button><button className="primary-button" type="submit">{dialog === "create" ? "Anlegen" : "Speichern"}</button></div></form></div></div>}
  </div>;
}
